ubuntu@hotel-management-server:~$ sudo systemctl status gunicorn
● gunicorn.service - gunicorn daemon for hotel-management-backend
     Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; vendor preset: enabled)
     Active: active (running) since Sat 2025-08-23 06:25:23 UTC; 6 days ago
   Main PID: 2417050 (gunicorn)
      Tasks: 4 (limit: 28689)
     Memory: 232.5M
        CPU: 1min 15.605s
     CGroup: /system.slice/gunicorn.service
             ├─2417050 /home/ubuntu/hotel-management-backend/venv/bin/python3 /home/ubuntu/hotel-management-backend/venv/bin/gunicorn --workers 3 --bind 127.0.0.1:8000 con>
             ├─2417052 /home/ubuntu/hotel-management-backend/venv/bin/python3 /home/ubuntu/hotel-management-backend/venv/bin/gunicorn --workers 3 --bind 127.0.0.1:8000 con>
             ├─2417053 /home/ubuntu/hotel-management-backend/venv/bin/python3 /home/ubuntu/hotel-management-backend/venv/bin/gunicorn --workers 3 --bind 127.0.0.1:8000 con>
             └─2417054 /home/ubuntu/hotel-management-backend/venv/bin/python3 /home/ubuntu/hotel-management-backend/venv/bin/gunicorn --workers 3 --bind 127.0.0.1:8000 con>

Aug 29 15:47:46 hotel-management-server gunicorn[2417053]:     return executor(sql, params, many, context)
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/django/db/backends/utils.py", li>
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]:     with self.db.wrap_database_errors:
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in>
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]:   File "/home/ubuntu/hotel-management-backend/venv/lib/python3.10/site-packages/django/db/backends/utils.py", li>
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]:     return self.cursor.execute(sql, params)
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]: django.db.utils.IntegrityError: null value in column "can_access_kitchen" of relation "users_customuser" violate>
Aug 29 15:47:46 hotel-management-server gunicorn[2417053]: DETAIL:  Failing row contains (7, pbkdf2_sha256$600000$GGz62m35t8MaadX4rb15Qz$04OND1S1czqDBRFNsL8q..., null, f, >
Aug 29 15:48:15 hotel-management-server gunicorn[2417052]: Failed WhatsApp to whatsapp:+917697480580: HTTP 400 error: Unable to create record: Twilio could not find a Chan>
lines 1-23/23 (END)
